### PR TITLE
Add an option to return each row as an object keyed by column name

### PR DESCRIPTION
**Pull request by ctranstrum**
This is one approach for resolving #24

### CODE REVIEW

**Review by platypii — CHANGES_REQUESTED** [review]
Nice changes! Thanks @ctranstrum 

Overall this looks good. Some feedback:

- Would like a test for this option in `read.test.js`
- Update type `ParquetReadOptions` in `hyparquet.d.ts` with `rowObjects`
- Update type for `onComplete` from `any[][]` to `object[]` and associated type changes needed in a few places in `read.js` and `demo.js` and `hyparquet.d.ts`
- Fix lint error

**Comment by ctranstrum** [comment]
Got thinking about the name, and my original choice didn't seem ideal in the event someday in the future someone wants to add a different format. So instead of `rowObjects: true`, I think `rowFormat: 'object'` is more extensible.

**Review by platypii — APPROVED** [review]
This looks nice. I like the string option more than the boolean flag. 

Thanks @ctranstrum !

**Comment by hax** [comment]
Great! When will the new version release?

**Comment by platypii** [comment]
Just published v1.2.0 with option `rowFormat: 'object'`

**Pull request merged**
