### PR TITLE
Test readColumnIndex and readOffsetIndex

### PR DESCRIPTION
**Pull request by park-brian**
This is a preliminary pull request to add tests for readColumnIndex and readOffsetIndex.

When available, column and offset indices were saved to:
- test/files/{base_name}.column_indices.json
- test/files/{base_name}.offset_indices.json

All offset indexes were parsed successfully. However, two test files had column indices that could not be parsed (both had issues when using convertMetadata on the min_values/max_values). Details are as follows:

File: `test/files/adam_genotypes.parquet`
This file has pages containing only null records, which results in 0-length Uint8Arrays representing INT64s being passed to the convertMetadata function. We can treat empty Uint8Arrays as null values or avoid parsing them.

File: `test/files/duckdb5533.parquet`
This file has pages where the min_values or max_values are variable-length Uint8Arrays, but are mapped to the INT32 Type. Specifically, Uint8Array(1) [ 0 ] results in a RangeError when passed to view.getInt32(0, true), since it is less than four bytes long. We can probably add length qualifiers to the convertMetadata function's type conditions, or simply assume that any Uint8Arrays less than the minimum length for Int32/64 already have the most/least significant bytes filled in. I personally feel that length checks might be a safer approach. It's also possible that DuckDB just generated a file with bad column indexes.

### CODE REVIEW

**Comment by park-brian** [comment]
It looks like `duckdb5533.parquet` was actually generated by Arrow2 (Rust)

**Comment by platypii** [comment]
@park-brian Thanks for the great PR!

I agree that the right answer is probably length checks in `convertMetadata`. It does feel like these are invalid parquet files, but my preference is to be forgiving about reading parquet files in the wild. I just pushed a commit to your PR with my suggestion there.

I am reluctant to return undefined when length === 0, as I think that will incorrectly catch the case where a min/max value is actually empty string "". I am open to being convinced here though. Could also catch it with a more carefully constructed conditional in `convertMetadata` but I'm not sure it's necessary?

Let me know if this aligns with your thinking.

**Comment by park-brian** [comment]
I had completely forgotten about zero-length strings! In that case, I totally agree that length checks are sufficient for both cases.

**Comment by park-brian** [comment]
@platypii 
I just noticed there might be a small typo in the `indicies.js` filename. I think it might be spelled `indices.js`. There's also `indexes`, which is considered a more "modern" pluralization.

**Comment by platypii** [comment]
> @platypii I just noticed there might be a small typo in the `indicies.js` filename. I think it might be spelled `indices.js`. There's also `indexes`, which is considered a more "modern" pluralization.

Fair point, I mostly didn't want to use "index.js" which has special meaning. If you want to rename it to "indexes.js" or something else I would support that. I plan to review and merge this PR in the next day or so. Thanks!

**Comment by park-brian** [comment]
Thank you! I've renamed it to "indexes" for now. Let me know if this looks good to you.

**Review by platypii — APPROVED** [review]
Thanks so much for adding these great tests, and working through those edges cases!

**Comment by park-brian** [comment]
Any time! Thank you for accepting the PR. Next up: potential work on parquetQuery (still TBD)

**Pull request merged**
