### PR TITLE
build types before publishing to npm

### LINKED ISSUE #43: generate the types automatically
We currently have two definitions for the types. For example, asyncBufferFromUrl is not synchronized between the implementation and the type declaration (after #34):

https://github.com/hyparam/hyparquet/blob/c85d38eed53fa0a0547d35513d345cdb73ca58c3/src/utils.js#L56-L66

https://github.com/hyparam/hyparquet/blob/c85d38eed53fa0a0547d35513d345cdb73ca58c3/src/hyparquet.d.ts#L117-L121

### PR DESCRIPTION
**Pull request by severo**
fixes #43

- [x] build the types before publishing to npm
- [x] handle the two d.ts. files in src, and fix the duplicate types
- [x] <strike>one bundled .d.ts file, or</strike> keep a hierarchy of directories and files?
- [x] test the generated types with tsd? https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#tips -> no
- [x] ensure it works as expected.

I ran `npm pack` and used that package in https://github.com/hyparam/hyperparam-cli components and hyparquet-demo. It showed some errors that I fixed with https://github.com/hyparam/hyparquet/pull/46/commits/8e62c07d9b9bdf22b2d9a2c3d96a77d81caccf3d (in these apps we directly import the types from `hyparquet`, not from `hyparquet/src/types.d.ts`).

We emit types/(file).d.ts AND types/(file).d.ts.map because I enabled https://www.typescriptlang.org/tsconfig/#declarationMap. I'm not 100% sure we need it, but it seems recommended.

Also, I'm not sure why the CI failed at some point (https://github.com/hyparam/hyparquet/actions/runs/12047750237/job/33590915755). I could not reproduce the errors locally, and they are weird (for example, we allow importing from JSON with `"resolveJsonModule": true,` in tsconfig.json, so the last error does not make much sense to me).

Update: I think the errors come from typescript 5.7:
- import json: https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#validated-json-imports-in---module-nodenext
- ArrayBuffer: https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#notable-behavioral-changes

The GitHub action was using `tsc`, ie the globally installed typescript binary, which happens to now be 5.7, and not 5.6.3 as locally installed. We could just have replaced `tsc` with `npx tsc`, or we could also upgrade to 5.7 and fix the issues.

### CODE REVIEW

**Comment by platypii** [comment]
Pushed changes to use new jsdoc `@import` syntax that was added in typescript 5.5. The upside is that typescript emits smaller declaration files with `@import` vs `@typedef`. 160kb -> 145kb unpacked size.

**Comment by platypii** [comment]
The generated declarations are a lot larger than before (117kb -> 143kb). Mostly because it's emitting types for a bunch of internal functions. This is understandable, and maybe even the right thing to do? But I experimented with various options:

## `@private` / `@internal` jsdoc annotations

I wanted to not expose internal functions, since I don't want users to depend on them and then make it painful to evolve the internal code. In theory, you can annotate with jsdoc tag `@internal` and use tsconfig option `"stripInternal": true` but it doesn't work for me? [[1]](https://www.typescriptlang.org/tsconfig/#stripInternal) [[2]](https://github.com/microsoft/TypeScript/issues/38444)

## removeComments

If you set tsconfig option `"removeComments": true` it will strip the comments from the generated .d.ts files. This results in much smaller package (129.3kb). But when you try to use the package as a dependency in vscode, the hints no longer show the documentation. Not acceptable.

## Combine js files and don't export

I did this for a few functions in `header.js` and `datapageV2.js` and `asyncBuffer.js` which saved a little bit, but I don't want to make one giant source file.

## Conclusion

There's probably ways to improve this with tooling, but I don't want to complicate the build process more. If you have ideas @severo let me know. Otherwise this is probably good for now and will just eat the increased package size. (anyone who bundles it downstream won't really be affected by declaration size, but I'm still trying to keep the package as small as possible)

**Comment by severo** [comment]
OK, thanks for sharing all the research.

https://api-extractor.com could help strip the declarations for the internal functions (as proposed in https://www.typescriptlang.org/tsconfig/#stripInternal) because I don't think we want to rely on another build tool. Anyway, we might want to add `@internal` as a hint for developers not to rely on these functions (and explain it in the README).

I have no specific idea to reduce the size

**Review by platypii — APPROVED** [review]

**Comment by ngbrown** [comment]
I'm getting a type error when using `parquetRead` and passing the `utf8` option which appears to be related to this change. See #50.

**Pull request merged**
